"""Djlint tests for ignoring.

Many tests from from prettier.io's html test suite.

Where applicable this notice may be needed:

#### Prettier.io license ####
Copyright © James Long and contributors
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

run::

   pytest tests/test_html/test_ignore.py --cov=src/djlint --cov-branch \
          --cov-report xml:coverage.xml --cov-report term-missing

   pytest tests/test_html/test_ignore.py::test_long_attributes --cov=src/djlint --cov-branch \
          --cov-report xml:coverage.xml --cov-report term-missing

"""

from typing import TextIO

from click.testing import CliRunner

from ..conftest import reformat


def test_cases(runner: CliRunner, tmp_file: TextIO) -> None:

    html_in = (b"""
123<!--prettier-ignore-->456
<span></span><!--prettier-ignore--><span></span>
    """).strip()

    html_out = ("""
123<!--prettier-ignore-->456
<span></span
><!--prettier-ignore--><span></span>
        """).strip()

    output = reformat(
        tmp_file,
        runner,
        html_in)
def test_document(runner: CliRunner, tmp_file: TextIO) -> None:

    html_in = (b"""
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Title</title>
  </head>
  <body>
    <!-- prettier-ignore -->
    <p>
      Test  Test   Test
    </p>
    <!-- prettier-ignore -->
    <p attribute  =  "value">
      Test  Test   Test
    </p>
    <!-- prettier-ignore -->
    <ul
      ><li> First  </li
      ><li>Second<i>1</i><div><div>String</div></div></li
    ></ul>
    <!-- prettier-ignore -->
    <div>
    </div>
    <!-- prettier-ignore -->
    <ul><!--
      --><li>   First   </li><!--
      --><li>   Second   </li><!--
    --></ul>
    <!-- prettier-ignore -->
    <br />
  </body>
</html>
    """).strip()

    html_out = ("""
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Title</title>
  </head>
  <body>
    <!-- prettier-ignore -->
    <p>
      Test  Test   Test
    </p>
    <!-- prettier-ignore -->
    <p attribute  =  "value">
      Test  Test   Test
    </p>
    <!-- prettier-ignore -->
    <ul
      ><li> First  </li
      ><li>Second<i>1</i><div><div>String</div></div></li
    ></ul>
    <!-- prettier-ignore -->
    <div>
    </div>
    <!-- prettier-ignore -->
    <ul><!--
      --><li>   First   </li><!--
      --><li>   Second   </li><!--
    --></ul>
    <!-- prettier-ignore -->
    <br />
  </body>
</html>
        """).strip()

    output = reformat(
        tmp_file,
        runner,
        html_in)
def test_long_lines(runner: CliRunner, tmp_file: TextIO) -> None:

    html_in = (b"""
<!-- prettier-ignore -->
A super long string that has been marked as ignore because it was probably generated by some script.
<p>
    Just some ordinary text that should be wrapped up because it is super long and has not been marked as ignore.
</p>
<p>
    <!-- prettier-ignore -->
    A super long string that has been marked as ignore because it was probably generated by some script.
</p>
<!-- prettier-ignore -->
| Dogs | Cats | Weasels | Bats | Pigs | Mice | Hedgehogs | Capybaras | Rats | Tigers |
| ---- | ---- | ------- | ---- | ---- | ---- | --------- | --------- | ---- | ------ |
|    1 |    1 |       0 |    0 |    1 |    1 |         5 |        16 |    4 |      0 |
    """).strip()

    html_out = ("""
<!-- prettier-ignore -->
A super long string that has been marked as ignore because it was probably generated by some script.
<p>
  Just some ordinary text that should be wrapped up because it is super long and
  has not been marked as ignore.
</p>
<p>
  <!-- prettier-ignore -->
  A super long string that has been marked as ignore because it was probably generated by some script.
</p>
<!-- prettier-ignore -->
| Dogs | Cats | Weasels | Bats | Pigs | Mice | Hedgehogs | Capybaras | Rats | Tigers |
| ---- | ---- | ------- | ---- | ---- | ---- | --------- | --------- | ---- | ------ |
|    1 |    1 |       0 |    0 |    1 |    1 |         5 |        16 |    4 |      0 |
================================================================================
        """).strip()

    output = reformat(
        tmp_file,
        runner,
        html_in)
