from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Final

# whitespace css collapses to a single space and drops at a line edge.
# any other whitespace (e.g. u+2005) is rendered as written, so it is
# content rather than layout and must survive formatting.
COLLAPSIBLE_WHITESPACE: Final = " \t\n\r\f"

HTML_TAG_NAMES: Final = frozenset((
    "a",
    "abbr",
    "acronym",
    "address",
    "applet",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "basefont",
    "bdi",
    "bdo",
    "bgsound",
    "big",
    "blink",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "center",
    "cite",
    "code",
    "col",
    "colgroup",
    "command",
    "content",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "element",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "image",
    "img",
    "input",
    "ins",
    "isindex",
    "kbd",
    "keygen",
    "label",
    "legend",
    "li",
    "link",
    "listing",
    "main",
    "map",
    "mark",
    "marquee",
    "math",
    "menu",
    "menuitem",
    "meta",
    "meter",
    "multicol",
    "nav",
    "nextid",
    "nobr",
    "noembed",
    "noframes",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "plaintext",
    "pre",
    "progress",
    "q",
    "rb",
    "rbc",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "selectedcontent",
    "shadow",
    "slot",
    "small",
    "source",
    "spacer",
    "span",
    "strike",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "tt",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
    "xmp",
))

HTML_INLINE_ELEMENTS: Final = frozenset((
    "a",
    "abbr",
    "acronym",
    "b",
    "bdi",
    "bdo",
    "big",
    "cite",
    "code",
    "data",
    "del",
    "dfn",
    "em",
    "font",
    "i",
    "ins",
    "kbd",
    "mark",
    "q",
    "s",
    "samp",
    "small",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "u",
    "var",
))

# elements that lay out a box of their own rather than letting text run
# through them; their content, if any, is laid out apart from it.
HTML_ATOMIC_INLINE_ELEMENTS: Final = frozenset((
    "audio",
    "button",
    "canvas",
    "embed",
    "iframe",
    "img",
    "input",
    "math",
    "meter",
    "object",
    "progress",
    "select",
    "svg",
    "textarea",
    "video",
))

# elements that lay out an inline-level box, so a line break written
# against one renders as a space. the rest either start a block box, where
# whitespace at the edge is dropped, or render nothing at all.
HTML_INLINE_LEVEL_ELEMENTS: Final = (
    HTML_INLINE_ELEMENTS
    | HTML_ATOMIC_INLINE_ELEMENTS
    # inline or display: contents - text runs through these
    | frozenset(("label", "output", "picture"))
)

HTML_VOID_ELEMENTS: Final = frozenset((
    "area",
    "base",
    "basefont",
    "bgsound",
    "br",
    "col",
    "command",
    "embed",
    "frame",
    "hr",
    "image",
    "img",
    "input",
    "isindex",
    "keygen",
    "link",
    "menuitem",
    "meta",
    "nextid",
    "param",
    "source",
    "track",
    "wbr",
))

# elements whose content is text, not markup: a "<" inside one starts no tag
HTML_RAW_TEXT_ELEMENTS: Final = frozenset((
    "script",
    "style",
    "textarea",
    "title",
))
