name: Publish
on:
  push:
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-compiled:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-26
          - macos-26-intel
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-11-arm
          - windows-2025
      fail-fast: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          python-version: "3.14"
          enable-cache: false
      - run: uvx --exclude-newer '3 days' --no-cache cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: wheels-${{ matrix.os }}
          path: dist
  build-pure:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          python-version: "3.14"
          enable-cache: false
      - run: uv build --no-cache
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: wheels-any
          path: dist
  publish-pypi:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    needs:
      - build-compiled
      - build-pure
    permissions:
      id-token: write
    steps:
      - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          python-version: "3.14"
          enable-cache: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      - run: mkdir dist
      - run: mv wheels-*/* dist
      - run: uv publish --trusted-publishing always --no-cache
  publish-npm:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    needs:
      - publish-pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          check-latest: true
          package-manager-cache: false
          registry-url: https://registry.npmjs.org
      - run: npm publish --access public
